# Generated by Django 6.0.2 on 2026-02-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicklog',
            name='accept_language',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='as_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='browser',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='browser_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='country_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='device_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='device_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='is_hosting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='isp',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='org',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='os',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='os_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='referrer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='region_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='timezone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
